/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "approvalsRequired",
                type: "uint256",
            },
        ],
        name: "ApprovalsRequirementChanged",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "multisigAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "emitter",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "required",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bool",
                name: "requireExecution",
                type: "bool",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "transactionExpiry",
                type: "uint256",
            },
        ],
        name: "EndowmentMultisigCreated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "transactionExpiry",
                type: "uint256",
            },
        ],
        name: "ExpiryChanged",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint8",
                name: "version",
                type: "uint8",
            },
        ],
        name: "Initialized",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "currOwner",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnerReplaced",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
        ],
        name: "OwnersAdded",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
        ],
        name: "OwnersRemoved",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bool",
                name: "requireExecution",
                type: "bool",
            },
        ],
        name: "RequireExecutionChanged",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
        ],
        name: "TransactionConfirmationRevoked",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
        ],
        name: "TransactionConfirmed",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
        ],
        name: "TransactionExecuted",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "metadata",
                type: "bytes",
            },
        ],
        name: "TransactionSubmitted",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "approvalsRequired",
                type: "uint256",
            },
        ],
        name: "approvalsRequirementChangedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "multisigAddress",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "emitter",
                type: "address",
            },
            {
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
            {
                internalType: "uint256",
                name: "required",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "requireExecution",
                type: "bool",
            },
            {
                internalType: "uint256",
                name: "transactionExpiry",
                type: "uint256",
            },
        ],
        name: "createEndowmentMultisig",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "transactionExpiry",
                type: "uint256",
            },
        ],
        name: "expiryChangedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_multisigFactory",
                type: "address",
            },
        ],
        name: "initEndowmentMultiSigEmitter",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "currOwner",
                type: "address",
            },
            {
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "ownerReplacedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
        ],
        name: "ownersAddedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
        ],
        name: "ownersRemovedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "requireExecution",
                type: "bool",
            },
        ],
        name: "requireExecutionChangedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
        ],
        name: "transactionConfirmationRevokedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
        ],
        name: "transactionConfirmedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
        ],
        name: "transactionExecutedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "endowmentId",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "transactionId",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "metadata",
                type: "bytes",
            },
        ],
        name: "transactionSubmittedEndowment",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
export class Emitter__factory {
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
Emitter__factory.abi = _abi;
