"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountsUpdateEndowmentSettingsController__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "key",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "currVal",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "decrVal",
                type: "uint256",
            },
        ],
        name: "DecrAmountExceedsValue",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "key",
                type: "address",
            },
        ],
        name: "NonExistentKey",
        type: "error",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "spender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "AllowanceSpent",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "spender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "newBalance",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "added",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "deducted",
                type: "uint256",
            },
        ],
        name: "AllowanceUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [],
        name: "ConfigUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint32[]",
                name: "add",
                type: "uint32[]",
            },
            {
                indexed: false,
                internalType: "uint32[]",
                name: "remove",
                type: "uint32[]",
            },
        ],
        name: "DafApprovedEndowmentsUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "donationMatchContract",
                type: "address",
            },
        ],
        name: "DonationMatchCreated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "enum LibAccounts.AllowlistType",
                name: "allowlistType",
                type: "uint8",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "add",
                type: "address[]",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "remove",
                type: "address[]",
            },
        ],
        name: "EndowmentAllowlistUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                components: [
                    {
                        components: [
                            {
                                internalType: "uint32",
                                name: "endowId",
                                type: "uint32",
                            },
                            {
                                internalType: "address",
                                name: "addr",
                                type: "address",
                            },
                        ],
                        internalType: "struct LibAccounts.BeneficiaryData",
                        name: "data",
                        type: "tuple",
                    },
                    {
                        internalType: "enum LibAccounts.BeneficiaryEnum",
                        name: "enumData",
                        type: "uint8",
                    },
                ],
                indexed: false,
                internalType: "struct LibAccounts.Beneficiary",
                name: "beneficiary",
                type: "tuple",
            },
            {
                indexed: false,
                internalType: "uint32[]",
                name: "relinked",
                type: "uint32[]",
            },
        ],
        name: "EndowmentClosed",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "enum LibAccounts.EndowmentType",
                name: "endowType",
                type: "uint8",
            },
        ],
        name: "EndowmentCreated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amountLocked",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amountLiquid",
                type: "uint256",
            },
        ],
        name: "EndowmentDeposit",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bytes4",
                name: "strategy",
                type: "bytes4",
            },
            {
                indexed: false,
                internalType: "string",
                name: "network",
                type: "string",
            },
            {
                indexed: false,
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "lockAmt",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "liquidAmt",
                type: "uint256",
            },
        ],
        name: "EndowmentInvested",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bytes4",
                name: "strategy",
                type: "bytes4",
            },
            {
                indexed: false,
                internalType: "string",
                name: "network",
                type: "string",
            },
            {
                indexed: false,
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "lockAmt",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "liquidAmt",
                type: "uint256",
            },
        ],
        name: "EndowmentRedeemed",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "string",
                name: "setting",
                type: "string",
            },
        ],
        name: "EndowmentSettingUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
        ],
        name: "EndowmentUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "enum IVault.VaultType",
                name: "accountType",
                type: "uint8",
            },
            {
                indexed: false,
                internalType: "address",
                name: "beneficiaryAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "beneficiaryEndowId",
                type: "uint32",
            },
        ],
        name: "EndowmentWithdraw",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "owner",
                type: "address",
            },
        ],
        name: "OwnerUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                components: [
                    {
                        internalType: "string",
                        name: "destinationChain",
                        type: "string",
                    },
                    {
                        internalType: "bytes4",
                        name: "strategyId",
                        type: "bytes4",
                    },
                    {
                        internalType: "bytes4",
                        name: "selector",
                        type: "bytes4",
                    },
                    {
                        internalType: "uint32[]",
                        name: "accountIds",
                        type: "uint32[]",
                    },
                    {
                        internalType: "address",
                        name: "token",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "lockAmt",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "liqAmt",
                        type: "uint256",
                    },
                    {
                        internalType: "enum IVault.VaultActionStatus",
                        name: "status",
                        type: "uint8",
                    },
                ],
                indexed: false,
                internalType: "struct IVault.VaultActionData",
                name: "",
                type: "tuple",
            },
        ],
        name: "RefundNeeded",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "endowId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "enum IVault.VaultType",
                name: "accountType",
                type: "uint8",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenIn",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amountIn",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenOut",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amountOut",
                type: "uint256",
            },
        ],
        name: "TokenSwapped",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                components: [
                    {
                        internalType: "string",
                        name: "destinationChain",
                        type: "string",
                    },
                    {
                        internalType: "bytes4",
                        name: "strategyId",
                        type: "bytes4",
                    },
                    {
                        internalType: "bytes4",
                        name: "selector",
                        type: "bytes4",
                    },
                    {
                        internalType: "uint32[]",
                        name: "accountIds",
                        type: "uint32[]",
                    },
                    {
                        internalType: "address",
                        name: "token",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "lockAmt",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "liqAmt",
                        type: "uint256",
                    },
                    {
                        internalType: "enum IVault.VaultActionStatus",
                        name: "status",
                        type: "uint8",
                    },
                ],
                indexed: false,
                internalType: "struct IVault.VaultActionData",
                name: "",
                type: "tuple",
            },
        ],
        name: "UnexpectedTokens",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint32",
                name: "id",
                type: "uint32",
            },
            {
                internalType: "enum LibAccounts.AllowlistType",
                name: "allowlistType",
                type: "uint8",
            },
            {
                internalType: "address[]",
                name: "add",
                type: "address[]",
            },
            {
                internalType: "address[]",
                name: "remove",
                type: "address[]",
            },
        ],
        name: "updateEndowmentAllowlist",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "uint32",
                        name: "id",
                        type: "uint32",
                    },
                    {
                        components: [
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "acceptedTokens",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "lockedInvestmentManagement",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "liquidInvestmentManagement",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "allowlistedBeneficiaries",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "allowlistedContributors",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "maturityAllowlist",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "maturityTime",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "earlyLockedWithdrawFee",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "withdrawFee",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "depositFee",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "balanceFee",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "name",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "image",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "logo",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "sdgs",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "splitToLiquid",
                                type: "tuple",
                            },
                            {
                                components: [
                                    {
                                        internalType: "bool",
                                        name: "locked",
                                        type: "bool",
                                    },
                                    {
                                        components: [
                                            {
                                                internalType: "address",
                                                name: "addr",
                                                type: "address",
                                            },
                                            {
                                                internalType: "uint256",
                                                name: "expires",
                                                type: "uint256",
                                            },
                                        ],
                                        internalType: "struct LibAccounts.Delegate",
                                        name: "delegate",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct LibAccounts.SettingsPermission",
                                name: "ignoreUserSplits",
                                type: "tuple",
                            },
                        ],
                        internalType: "struct LibAccounts.SettingsController",
                        name: "settingsController",
                        type: "tuple",
                    },
                ],
                internalType: "struct AccountMessages.UpdateEndowmentControllerRequest",
                name: "details",
                type: "tuple",
            },
        ],
        name: "updateEndowmentController",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "uint32",
                        name: "id",
                        type: "uint32",
                    },
                    {
                        internalType: "bool",
                        name: "donationMatchActive",
                        type: "bool",
                    },
                    {
                        internalType: "uint256",
                        name: "maturityTime",
                        type: "uint256",
                    },
                    {
                        components: [
                            {
                                internalType: "uint256",
                                name: "max",
                                type: "uint256",
                            },
                            {
                                internalType: "uint256",
                                name: "min",
                                type: "uint256",
                            },
                            {
                                internalType: "uint256",
                                name: "defaultSplit",
                                type: "uint256",
                            },
                        ],
                        internalType: "struct LibAccounts.SplitDetails",
                        name: "splitToLiquid",
                        type: "tuple",
                    },
                    {
                        internalType: "bool",
                        name: "ignoreUserSplits",
                        type: "bool",
                    },
                ],
                internalType: "struct AccountMessages.UpdateEndowmentSettingsRequest",
                name: "details",
                type: "tuple",
            },
        ],
        name: "updateEndowmentSettings",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "uint32",
                        name: "id",
                        type: "uint32",
                    },
                    {
                        components: [
                            {
                                internalType: "address",
                                name: "payoutAddress",
                                type: "address",
                            },
                            {
                                internalType: "uint256",
                                name: "bps",
                                type: "uint256",
                            },
                        ],
                        internalType: "struct LibAccounts.FeeSetting",
                        name: "earlyLockedWithdrawFee",
                        type: "tuple",
                    },
                    {
                        components: [
                            {
                                internalType: "address",
                                name: "payoutAddress",
                                type: "address",
                            },
                            {
                                internalType: "uint256",
                                name: "bps",
                                type: "uint256",
                            },
                        ],
                        internalType: "struct LibAccounts.FeeSetting",
                        name: "depositFee",
                        type: "tuple",
                    },
                    {
                        components: [
                            {
                                internalType: "address",
                                name: "payoutAddress",
                                type: "address",
                            },
                            {
                                internalType: "uint256",
                                name: "bps",
                                type: "uint256",
                            },
                        ],
                        internalType: "struct LibAccounts.FeeSetting",
                        name: "withdrawFee",
                        type: "tuple",
                    },
                    {
                        components: [
                            {
                                internalType: "address",
                                name: "payoutAddress",
                                type: "address",
                            },
                            {
                                internalType: "uint256",
                                name: "bps",
                                type: "uint256",
                            },
                        ],
                        internalType: "struct LibAccounts.FeeSetting",
                        name: "balanceFee",
                        type: "tuple",
                    },
                ],
                internalType: "struct AccountMessages.UpdateFeeSettingRequest",
                name: "details",
                type: "tuple",
            },
        ],
        name: "updateFeeSettings",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class AccountsUpdateEndowmentSettingsController__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.AccountsUpdateEndowmentSettingsController__factory = AccountsUpdateEndowmentSettingsController__factory;
AccountsUpdateEndowmentSettingsController__factory.abi = _abi;
