"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Router__factory = exports.Registrar__factory = exports.IndexFund__factory = exports.multiSig = exports.accounts = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.accounts = __importStar(require("./accounts"));
exports.multiSig = __importStar(require("./multiSig"));
var IndexFund__factory_1 = require("./IndexFund__factory");
Object.defineProperty(exports, "IndexFund__factory", { enumerable: true, get: function () { return IndexFund__factory_1.IndexFund__factory; } });
var Registrar__factory_1 = require("./Registrar__factory");
Object.defineProperty(exports, "Registrar__factory", { enumerable: true, get: function () { return Registrar__factory_1.Registrar__factory; } });
var Router__factory_1 = require("./Router__factory");
Object.defineProperty(exports, "Router__factory", { enumerable: true, get: function () { return Router__factory_1.Router__factory; } });
